# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - AppPedidosComidas

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Restore dependencies
        run: dotnet restore App-PedidosComidas.sln
      
      - name: Build Application
        run: dotnet build App-PedidosComidas.sln --configuration Release --no-restore
      
      - name: Publish Application
        run: dotnet publish ./App-PedidosComidas/Presentation.csproj --configuration Release --output ./myapp
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
        
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F29369FF7B57427CA58BD07B42452C7E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A0376C0977F410FADD7461E686EA0F3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1231AE1E57F64751A67561269590941E }}

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef --version 8.*

      - name: Update database with EF Core migrations
        run: dotnet ef database update --project ./Infrastructure/Infrastructure.csproj --startup-project ./App-PedidosComidas/Presentation.csproj
        env: 
            ASPNETCORE_ENVIRONMENT: Production

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AppPedidosComidas'
          slot-name: 'Production'
          package: .